# Povio GitHub Actions workflow configuration
# version 1.0.0

name: Firebase Deploy (Staging)
on:
  push:
    tags:
      - 'staging/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  deploy:
    name: Deployment
    runs-on: macos-latest-xlarge

    env:
      ENVIRONMENT: 'sta'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Load Latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: "SourcePackages/"
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      - name: Setup SSH Keys
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Get Tag Name
        uses: olegtarasov/get-tag@v2.1

      - name: Fastlane Deploy 
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          APP_STORE_CONNECT_API_ISSUER_ID: '${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}'
          APP_STORE_CONNECT_API_KEY_CONTENT: '${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}'
          APP_STORE_CONNECT_API_KEY_ID: '${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}'
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SLACK_CLIENT_CHANNEL: '${{ secrets.SLACK_CLIENT_CHANNEL }}'
          SLACK_DEFAULT_CHANNEL: '${{ secrets.SLACK_DEFAULT_CHANNEL }}'
          SENTRY_TOKEN: '${{ secrets.SENTRY_AUTH_TOKEN }}'
          FIREBASE_CLI_TOKEN: '${{ secrets.FIREBASE_CLI_TOKEN }}'
        run: bundle exec fastlane deploy_app --env ${{ env.ENVIRONMENT }}

      - name: Slack Notify
        env:
          APP_STORE_CONNECT_API_ISSUER_ID: '${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}'
          APP_STORE_CONNECT_API_KEY_CONTENT: '${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}'
          APP_STORE_CONNECT_API_KEY_ID: '${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}'
          SLACK_CLIENT_CHANNEL: '${{ secrets.SLACK_CLIENT_CHANNEL }}'
          SLACK_DEFAULT_CHANNEL: '${{ secrets.SLACK_DEFAULT_CHANNEL }}'
          SLACK_ACCESS_TOKEN: '${{ secrets.SLACK_ACCESS_TOKEN }}'
        run: bundle exec fastlane sendMessage --env ${{ env.ENVIRONMENT }}
