name: Register New Device
on:
  workflow_dispatch:
    inputs:
      device_name:
        description: 'Device name'
        required: true
      device_udid:
        description: 'Device UDID'
        required: true

jobs:
  test:
    name: Register New Device
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Register new device
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          APP_STORE_CONNECT_API_ISSUER_ID: '${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}'
          APP_STORE_CONNECT_API_KEY_CONTENT: '${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}'
          APP_STORE_CONNECT_API_KEY_ID: '${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}'
        run: bundle exec fastlane register_new_device device_name:"${{ github.event.inputs.device_name }}" device_udid:"${{ github.event.inputs.device_udid }}"
