name: Testing
on: workflow_dispatch

jobs:
  test:
    name: Running Tests
    runs-on: macos-12
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: "SourcePackages/"
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      - name: Lint Code
        env:
          APP_STORE_CONNECT_API_ISSUER_ID: '${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}'
          APP_STORE_CONNECT_API_KEY_CONTENT: '${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}'
          APP_STORE_CONNECT_API_KEY_ID: '${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}'
        run: bundle exec fastlane lint

      - name: Run Tests
        env:
          SCAN_SCHEME: "template Dev"
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          APP_STORE_CONNECT_API_ISSUER_ID: '${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}'
          APP_STORE_CONNECT_API_KEY_CONTENT: '${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}'
          APP_STORE_CONNECT_API_KEY_ID: '${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}'
        run: bundle exec fastlane test device:"iPhone 13 Pro" version:"15.5" unit:true ui:false
